global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'plc-service'
    static_configs:
      - targets: ['plc-service:8000']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']

  - job_name: 'alarm-service'
    static_configs:
      - targets: ['alarm-service:8002']
